### ISSUE TITLE
Restlet dependencies breaking Apache Solr build

### ISSUE THREAD

**Issue by joel-bernstein** [restlet/restlet-framework-java#1366]
Virtually all releases of Apache Solr can no longer be built due to the inability to resolve the reslet dependencies. On top of this all projects that have Apache Solr as a dependency cannot be built due to the inability to resolve the dependencies.

The root cause of this appears to be the redirect from **http** to **https** that occurs when accessing the dependencies on maven.restlet.org. There is also a redirect occurring to maven.restlet.talend.com but this does not appear to be the root cause. But avoiding this redirect would simplify the access to the reslet dependencies as well.

**Comment by uschindler** [comment]
The reason why this is a problem is that Java's networking API behind the URL class does not gooloe redirects that change protocol. This causes a file not found. Newer Maven versions seem to have a workaround for this, but Apache Ivy and tools relying on it break by this.

It would be good to keep the old URL alive and remove the forceful redirection.

**Comment by uschindler** [comment]
See the JDK issues explaining that:
https://bugs.openjdk.java.net/browse/JDK-4620571
https://bugs.openjdk.java.net/browse/JDK-4959149

**Comment by jlouvel** [comment]
Thanks for the report and root cause analysis. @thboileau and the team will look into fixing this issue ASAP.

**Comment by thboileau** [comment]
Hello all,
an update of the configuration of the front proxy has been requested and will be deployed tomorrow (about 10 am paris hour).
We will notify you when the fix is deployed.

**Comment by joel-bernstein** [comment]
Thanks, I'll test the Solr builds after I receive the notification and let you know if the issue is resolved.

**Comment by joel-bernstein** [comment]
@thboileau, is there an update on this? It does not appear that the proxy update has been applied yet.

**Comment by constint** [comment]
Hello,

We are moving towards the resolution of the issue, but unfortunately it is only partially solved.

We have removed the HTTP->HTTPS redirection on the primary domain `maven.restlet.talend.com`, which can now be accessed using both protocols.

Concerning the older domains `maven.restlet.org` and `maven.restlet.com`, the HTTPS redirection is still present unfortunately, but we have contacted the people in charge of it for a fix. 

If you are able to switch domains we would suggest using `maven.restlet.talend.com` as it will stay with the HTTP protocol if asked to.

Again, sorry for the inconvenience, we'll keep you apprised of new developments.

**Comment by joel-bernstein** [comment]
The latest releases of Solr have already been changed. The issue is that years of pre-existing Solr releases which have been deployed to maven central point to maven.restlet.org. These existing releases go back many years and are depended on by many builds around the world. These builds will continue to be broken until the HTTP-HTTPS redirect  on maven.restlet.org is removed.

**Comment by uschindler** [comment]
Latest Solr releases are using HTTPS (for security reasons). But what was released before cannot be changed anymore.

This is also one reason why Maven Central is accessible via HTTP without redirects, although there was a lot of discussion how to change this. But as the HTTP->HTTPS is not working for any Java release out there and older Versions of Maven cannot be changed, this is a problem that will stay like this forever.

**Comment by jlouvel** [comment]
Understood. We are definitely ensuring that we remove HTTP-HTTPS redirects on maven.restlet.org. Hopefully it should only take us a couple of days to fix.

**Comment by chatman** [comment]
In our builds (not Apache's Solr, but our own fork), switched maven.restlet.org to maven.restlet.com and it seems to work.
https://github.com/fullstorydev/lucene-solr/pull/43
Would be grateful if someone can please advise on our PR here ^.

**Comment by jlouvel** [comment]
@chatman Thanks for the note, I've reviewed your PR and commented there. Cheers

**Comment by joel-bernstein** [comment]
@jlouvel, Is there any update on the status of the http->https redirects for maven.restlet.org? This is what needs to be fixed to resolve this ticket.

**Comment by jlouvel** [comment]
@joel-bernstein Our team in charge of these redirections has confirmed us yesterday that they are working on a fix. We'll keep you posted as soon as this is fixed or when we have a ETA. Thx for your patience.

**Comment by jlouvel** [comment]
FYI, the redirection from maven.restlet.com to maven.restlet.talend.com now preserves the protocol (HTTP or HTTPS).

We are still working on maven.restlet.org redirection infrastructure, but for now to redirects always to HTTP, so it shouldn't break existing builds anymore.

Let us know if you see remaining issues with your builds.

**Comment by anbmic** [comment]
@jlouvel , it seems that all our build failed again starting from the beginning of Jan 16, did your team any change recently after the previous fix? 

`Failed to collect dependencies at org.apache.solr:solr-test-framework:jar:7.5.0 -> org.restlet.jee:org.restlet:jar:2.3.0: Failed to read artifact descriptor for org.restlet.jee:org.restlet:jar:2.3.0: Could not transfer artifact org.restlet.jee:org.restlet:pom:2.3.0 from/to maven-restlet (http://maven.restlet.org): Access denied to: http://maven.restlet.org/org/restlet/jee/org.restlet/2.3.0/org.restlet-2.3.0.pom , ReasonPhrase:Forbidden.`

**Comment by jlouvel** [comment]
Hi @anbmic Thanks for the report, I'm looking into this. It's likely related to the deployment of the new redirection from maven.restlet.org to maven.restlet.talend.com.

**Comment by jlouvel** [comment]
@anbmic We have completed the deployment of our redirections from maven.restlet.org to maven.restlet.talend.com, and from maven.restlet.com to maven.restlet.talend.com, while preserving the protocol (HTTP or HTTPS).

Can you confirm everything works again for you?

**Comment by anbmic** [comment]
> @anbmic We have completed the deployment of our redirections from maven.restlet.org to maven.restlet.talend.com, and from maven.restlet.com to maven.restlet.talend.com, while preserving the protocol (HTTP or HTTPS).
> 
> Can you confirm everything works again for you?

Yup, it's working now. Thanks!!

**Comment by jlouvel** [comment]
Great, thanks for the feedback. Closing the issue
